"""empty message

Revision ID: 10db367546ab
Revises: cf4b7e68a3e3
Create Date: 2024-04-16 14:08:46.076393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10db367546ab'
down_revision = 'cf4b7e68a3e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('completed', sa.BOOLEAN(), nullable=False),
    sa.Column('due_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
