"""empty message

Revision ID: 74fcdaa490f4
Revises: f8d5bd5f5b55
Create Date: 2024-04-15 14:12:52.556162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74fcdaa490f4'
down_revision = 'f8d5bd5f5b55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
